/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package provemax74.Vistas;

import java.awt.Font;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import provemax74.AccesoADatos.ProductoData;
import provemax74.Entidades.Producto;



/**
 *
 * @author lucia
 */
public class ProductosComprados extends javax.swing.JInternalFrame {
    
    private List <Producto> listaProd;
    private ProductoData prodData;
    private Producto prod;

    private DefaultTableModel modelo;
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
 
    /**
     * Creates new form ProductosComprados
     */
 
    public ProductosComprados() {
        initComponents();
        
        prodData = new ProductoData();
        
        modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int i, int i1) {
            return false;
        }
    };
   
        armarCabeceraTabla();
        jTproductos.getColumnModel().getColumn(1).setPreferredWidth(230); //Para agrandar el ancho de columan de nombre de producto
        jTproductos.getColumnModel().getColumn(2).setPreferredWidth(200); //Para agrandar el ancho de columan de descripcion
        jTproductos.getColumnModel().getColumn(3).setPreferredWidth(200); //Para agrandar el ancho de columan de precio
        jTproductos.getColumnModel().getColumn(5).setPreferredWidth(100); //Para agrandar el ancho de columan de estado
       
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
            //centerRenderer.setFont(centerRenderer.getFont().deriveFont(Font.BOLD));
            
             for (int i = 0; i < jTproductos.getColumnModel().getColumnCount(); i++) {
                jTproductos.getColumnModel().getColumn(i).setHeaderRenderer(centerRenderer);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRBporFecha = new javax.swing.JRadioButton();
        jRBentreFechas = new javax.swing.JRadioButton();
        jRBultimaComp = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTproductos = new javax.swing.JTable();
        jBbuscar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jBlimpiar = new javax.swing.JButton();
        jDC1 = new com.toedter.calendar.JDateChooser();
        jDCfecha = new com.toedter.calendar.JDateChooser();
        jDC2 = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1212, 738));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Lista de Productos Comprados");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setText("Elegir fecha:");
        jLabel2.setPreferredSize(new java.awt.Dimension(146, 23));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("Elegir fecha 1:");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setText("Elegir fecha 2:");

        buttonGroup1.add(jRBporFecha);
        jRBporFecha.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jRBporFecha.setText("Por fecha:");

        buttonGroup1.add(jRBentreFechas);
        jRBentreFechas.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jRBentreFechas.setText("Más comprados:");
        jRBentreFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBentreFechasActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBultimaComp);
        jRBultimaComp.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jRBultimaComp.setText("Última compra");

        jTproductos.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTproductos.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jTproductos.setPreferredSize(new java.awt.Dimension(100, 100));
        jTproductos.setRowHeight(30);
        jScrollPane1.setViewportView(jTproductos);
        if (jTproductos.getColumnModel().getColumnCount() > 0) {
            jTproductos.getColumnModel().getColumn(0).setResizable(false);
            jTproductos.getColumnModel().getColumn(2).setResizable(false);
        }

        jBbuscar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jBbuscar.setText("Buscar");
        jBbuscar.setPreferredSize(new java.awt.Dimension(150, 70));
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton2.setText("Salir");
        jButton2.setPreferredSize(new java.awt.Dimension(150, 70));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jBlimpiar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jBlimpiar.setText("Limpiar");
        jBlimpiar.setPreferredSize(new java.awt.Dimension(150, 70));
        jBlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimpiarActionPerformed(evt);
            }
        });

        jDC1.setPreferredSize(new java.awt.Dimension(200, 30));

        jDCfecha.setPreferredSize(new java.awt.Dimension(200, 30));

        jDC2.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jBlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(400, 400, 400))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBporFecha)
                            .addComponent(jRBultimaComp)
                            .addComponent(jRBentreFechas))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDCfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(jDC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                        .addGap(256, 256, 256)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jDCfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRBporFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRBentreFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jRBultimaComp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBentreFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBentreFechasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBentreFechasActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        // TODO add your handling code here:
        
        if (jRBporFecha.isSelected()) {

            cargarProductosPorFecha();

        } else if (jRBentreFechas.isSelected()) {
            //=======METODO para buscar los productos más comprados entre fechas =============
            cargarProductosEntreFechas();
        } else if (jRBultimaComp.isSelected()) {
           //=======METODO para buscar los productos de la última compra =============
            cargarProductosUltimaCompra();
        }
        
    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jBlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimpiarActionPerformed
        // TODO add your handling code here:
        borrarFilas();
        jDCfecha.setDate(null);
        jDC1.setDate(null);
        jDC2.setDate(null);

    }//GEN-LAST:event_jBlimpiarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void armarCabeceraTabla(){
        ArrayList<Object> filaCabecera=new ArrayList<>();
        filaCabecera.add("ID");
        filaCabecera.add("Nombre de Producto");
        filaCabecera.add("Descripcion");
        filaCabecera.add("Precio Unitario");
        filaCabecera.add("Stock");
        filaCabecera.add("Estado");
        for (Object it : filaCabecera) {
            modelo.addColumn(it);
            jTproductos.setModel(modelo);
       
        }
    }
 
    private void borrarFilas() {
        int indice = modelo.getRowCount() - 1;
        for (int i = indice; i >= 0; i--) {
            modelo.removeRow(i);
        }
        jRBporFecha.setSelected(false);
    }
    
     private void cargarProductosPorFecha() {

         LocalDate fecha = jDCfecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

         listaProd = prodData.obtenerProductosCompradosPorFecha(fecha);

         for (Producto p : listaProd) {

             modelo.addRow(new Object[]{p.getIdProducto(), p.getNombreProducto(), p.getDescripcion(), p.getPrecioActual(), p.getStock(), p.estado()});
             jTproductos.setDefaultRenderer(Object.class, centerRenderer); //para centrar los valores en las celdas de la tabla
        }
    }
      
      private void cargarProductosEntreFechas() {
//        int filas = modelo.getRowCount();
//        for (int i = filas - 1; i >= 0; i--) {
//            modelo.removeRow(i);
//        }

        try {
            if ((jDC1 != null) && (jDC2 != null)) {

                LocalDate fecha1 = jDC1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                LocalDate fecha2 = jDC2.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

                listaProd = prodData.listarProductosEntreFechas(fecha1, fecha2);

                if (fecha2.isBefore(fecha1)) {
                    // La fecha 2 es anterior a la fecha 1, muestra una advertencia.
                    JOptionPane.showMessageDialog(null, "La segunda fecha no puede ser anterior a la primera fecha.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else {

                    for (Producto producto : listaProd) {

                        modelo.addRow(new Object[]{producto.getNombreProducto(), producto.getDescripcion(),
                         producto.getPrecioActual(), prodData.sumarCantidadProductosCompradosEntreFechas(fecha1, fecha2).values()});
                        
                          jTproductos.setDefaultRenderer(Object.class, centerRenderer); //para centrar los valores en las celdas de la tabla

                    }
                }
            }

        } catch (NullPointerException np) {
            JOptionPane.showMessageDialog(this, "Falta ingresar una fecha", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }
      
     private void cargarProductosUltimaCompra(){
         listaProd=prodData.listarProductosDeUltimaCompra();
         for (Producto producto : listaProd) {

                modelo.addRow(new Object[]{producto.getNombreProducto(), producto.getDescripcion(),
                    producto.getPrecioActual(), producto.getStock()});
                
                 jTproductos.setDefaultRenderer(Object.class, centerRenderer); //para centrar los valores en las celdas de la tabla
            }
     }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBlimpiar;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDC1;
    private com.toedter.calendar.JDateChooser jDC2;
    private com.toedter.calendar.JDateChooser jDCfecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRBentreFechas;
    private javax.swing.JRadioButton jRBporFecha;
    private javax.swing.JRadioButton jRBultimaComp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTproductos;
    // End of variables declaration//GEN-END:variables
}
