/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package provemax74.Vistas;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import provemax74.AccesoADatos.ProductoData;
import provemax74.Entidades.Producto;



/**
 *
 * @author lucia
 */
public class ProductosComprados extends javax.swing.JInternalFrame {
    
    private List <Producto> listaProd;
    private ProductoData prodData;
    private Producto prod;

    private DefaultTableModel modelo;

    /**
     * Creates new form ProductosComprados
     */
   
    
    
    public ProductosComprados() {
        initComponents();
        
        prodData = new ProductoData();
        modelo = new DefaultTableModel();
        
        
        armarCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRBporFecha = new javax.swing.JRadioButton();
        jRBentreFechas = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTproductos = new javax.swing.JTable();
        jBbuscar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jBlimpiar = new javax.swing.JButton();
        jDC1 = new com.toedter.calendar.JDateChooser();
        jDCfecha = new com.toedter.calendar.JDateChooser();
        jDC2 = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1217, 778));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Lista de Productos");
        getContentPane().add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Elegir fecha:");
        getContentPane().add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Elegir fecha 1:");
        getContentPane().add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Elegir fecha 2:");
        getContentPane().add(jLabel4);

        buttonGroup1.add(jRBporFecha);
        jRBporFecha.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jRBporFecha.setText("Por fecha:");
        getContentPane().add(jRBporFecha);

        buttonGroup1.add(jRBentreFechas);
        jRBentreFechas.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jRBentreFechas.setText("Más comprados");
        jRBentreFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBentreFechasActionPerformed(evt);
            }
        });
        getContentPane().add(jRBentreFechas);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jRadioButton3.setText("De la última compra");
        getContentPane().add(jRadioButton3);

        jTproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTproductos);

        getContentPane().add(jScrollPane1);

        jBbuscar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jBbuscar.setText("Buscar");
        jBbuscar.setPreferredSize(new java.awt.Dimension(150, 80));
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jBbuscar);

        jButton2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton2.setText("Salir");
        jButton2.setPreferredSize(new java.awt.Dimension(150, 80));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);

        jBlimpiar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jBlimpiar.setText("Limpiar");
        jBlimpiar.setPreferredSize(new java.awt.Dimension(150, 80));
        jBlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jBlimpiar);

        jDC1.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(jDC1);

        jDCfecha.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(jDCfecha);

        jDC2.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(jDC2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBentreFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBentreFechasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBentreFechasActionPerformed

    private void armarCabeceraTabla(){
        ArrayList<Object> filaCabecera=new ArrayList<>();
        filaCabecera.add("ID");
        filaCabecera.add("Nombre de Producto");
        filaCabecera.add("Descripcion");
        filaCabecera.add("Precio Unitario");
        filaCabecera.add("Stock");
        filaCabecera.add("Estado");
        
        for (Object it: filaCabecera) {
        modelo.addColumn(it);
        jTproductos.setModel(modelo);
        }
    }
    
    
    private void borrarFilas() {
        int indice = modelo.getRowCount() - 1;
        for (int i = indice; i >= 0; i--) {
            modelo.removeRow(i);
        }
        jRBporFecha.setSelected(false);
    }
    
     private void cargarProductosPorFecha() {

        LocalDate localDate = jDCfecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        listaProd = prodData.obtenerProductosCompradosPorFecha(localDate);

        for (Producto p : listaProd) {

            modelo.addRow(new Object[]{p.getIdProducto(), p.getNombreProducto(), p.getDescripcion(), p.getPrecioActual(), p.getStock(), p.estado()});

        }

    }
      
      private void cargarProductosEntreFechas() {
        int filas = modelo.getRowCount();
        for (int i = filas - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }

        try {
            if ((jDC1 != null) && (jDC2 != null)) {

                LocalDate fecha1 = jDC1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                LocalDate fecha2 = jDC2.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

                List<Producto> productos = prodData.listarProductosEntreFechas(fecha1, fecha2);

                if (fecha2.isBefore(fecha1)) {
                    // La fecha 2 es anterior a la fecha 1, muestra una advertencia.
                    JOptionPane.showMessageDialog(null, "La segunda fecha no puede ser anterior a la primera fecha.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else {

                    for (Producto producto : productos) {

                        modelo.addRow(new Object[]{producto.getNombreProducto(), producto.getDescripcion(),
                            producto.getPrecioActual(), prodData.sumarCantidadProductosCompradosEntreFechas(fecha1, fecha2).values()});

                    }

                }

            }

        } catch (NullPointerException np) {
            JOptionPane.showMessageDialog(this, "Falta ingresar una fecha", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

    }
    
  
    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        // TODO add your handling code here:
        
         if (jRBporFecha.isSelected()) {
             
            cargarProductosPorFecha();
            
        } else if (jRBentreFechas.isSelected()) {
            //============== ACA AGREGAR EL METODO DE LOS PRODUCTOS MAS COMPRADOS ENTRE FECHA=============
  
           cargarProductosEntreFechas();
        }
 
    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jBlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimpiarActionPerformed
        // TODO add your handling code here:  
         borrarFilas();
        jRBporFecha.setSelected(false);
    }//GEN-LAST:event_jBlimpiarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBlimpiar;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDC1;
    private com.toedter.calendar.JDateChooser jDC2;
    private com.toedter.calendar.JDateChooser jDCfecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRBentreFechas;
    private javax.swing.JRadioButton jRBporFecha;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTproductos;
    // End of variables declaration//GEN-END:variables
}
